// demo-vue/app/components/Login.vue
<template>
  <Page>
    <GridLayout rows="*,auto,auto,*">
      <TextField margin="0 20 10 20" row="1" hint="UserName" :text="username"/>
      <Button margin="0 20" row="2" text="Enter" @tap="login"/>
    </GridLayout>
  </Page>
</template>

    <script>
    import SocketService from '../services/basic'
    import * as settings from 'tns-core-modules/application-settings';
export default {
  data() {
    return {
      username: ""
    };
  },
  computed:{
      socket: function(){
          return SocketService.getInstance();
      }
  },mounted() {
      this.socket.connect();
  },
  methods: {
    login(event) {
      this.socket.emit("add user", {
        username: this.username
      });
      settings.setString("me", this.username);
    }
  }
};
</script>

// demo-ng/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { SocketIO } from 'nativescript-socketio';
import { CallService } from '~/call.service';
import { RouterExtensions } from 'nativescript-angular/router';

@Component({
  moduleId: module.id,
  selector: 'login',
  templateUrl: 'login.component.html'
})
export class LoginComponent {
  username: string = '';

  constructor(
    private callService: CallService,
    private socket: SocketIO,
    private router: RouterExtensions
  ) {
    this.socket.on('login', data => {
      router.navigate(['/main']);
    });
  }

  login(event) {
    this.callService.currentUser = this.username;
    this.socket.emit('add user', {
      username: this.username
    });
  }
}

<GridLayout rows="*,auto,auto,*">
    <TextField margin="0 20 10 20" row="1" hint="UserName" [(ngModel)]="username"></TextField>
    <Button margin="0 20" row="2" text="Enter" (tap)="login($event)"></Button>
</GridLayout>
